name: 每5分钟执行Python脚本

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6
      
      - name: 设置 Python 环境
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: 安装依赖
        run: |
          pip install -r requirements.txt
      
      - name: 执行你的Python脚本
        run: python my_script.py
